version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8090:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins_home:
